### ISSUE TITLE
Conditionally wrapping `Element` causes an error, works without wrapping

### ISSUE THREAD

**Issue by TheGrimSilence** [prevwong/craft.js#382]
I'm trying to conditionally render either an `Elemen` or the actual dom node based on whether or not I'm editing or exporting. Currently my own solution for exporting the nodes to Next.js or HTML, otherwise it requires two separate copies of the same node, one for editing and one for exporting which I'm trying to avoid.

Copying the same `Element` implementation you have, I try to hand down the *exact* same information.

```ts
let isExporting = false;

export type Element<T extends React.ElementType> = {
  id?: NodeId;
  is?: T;
  custom?: Record<string, any>;
  children?: React.ReactNode;
  canvas?: boolean;
} & React.ComponentProps<T>;

export function Element<T extends React.ElementType>({
  id,
  children,
  ...props
}: Element<T>) {

  // const testElement1 = React.createElement(
  //   CraftElement,
  //   { id, is: "div", custom: props.custom, canvas: props.canvas },
  //   children
  // );

  const testElement2 = (
    <CraftElement id={id} {...props}>
      {children}
    </CraftElement>
  );

  return (isExporting
    ? (React.createElement(props.is, props.elementProps, children))
    : testElement2);

  // return (
  //   <CraftElement id={id} {...props}>
  //     {children}
  //   </CraftElement>
  // );
}
```

This actually works, but only as long as there are no children `Element`s, as having children causes 

> Error: Invariant failed: The component type specified for this node (Element) does not exist in the resolver

I've tried various implementations, all failing: directly supply the props, change the `is` to `div` to see if it's a scope issue, etc.

Is there any way I can get this to work?

**Comment by prevwong** [comment]
Where're you using this <Element /> component?

**Comment by prevwong** [comment]
Weird, would it be possible for you to create a codesandbox reproducing the behaviour?

**Comment by tsaunde123** [comment]
Has anyone managed to solve this? I appear to be having the same issue.

This is my user component that make use of the same `Element` component as @xsmithdev 

```
import React from "react";
import { Text } from "./Text";
import { Button } from "./Button";
import { Container } from "./Container";
import { Element } from "components/Element";

interface PromptProps {
  background?: string;
  padding?: number;
}

export const Prompt = ({ background = "#fff", padding = 20 }: PromptProps) => {
  return (
    <Element
      id="prompt-canvas"
      is={Container}
      background={background}
      padding={padding}
      canvas
    >
      <div className="text-only">
        <Text text="Title" fontSize={20} />
        <Text text="Subtitle" fontSize={15} />
      </div>
      <div className="buttons-only">
        <Button size="small" variant="contained" color="primary">
          Learn more
        </Button>
      </div>
    </Element>
  );
};

```

But it gives me the following error
`Error: Invariant failed: The component type specified for this node (fe) does not exist in the resolver`

**Comment by WilsonLe** [comment]
> Weird, would it be possible for you to create a codesandbox reproducing the behaviour?

I went ahead and reproduce the behavior. Basically I'm attempting to create a custom <Element/> that wraps around <CraftJSElement/> that takes an extra prop `isSSR`. If the <Element isSSR={true}/>, the element return a React element (rather than returning a CraftJSElement/>). 

https://codesandbox.io/s/craftjs-cond-element-9szcsl

**Comment by akucinskii** [comment]
Any update on this?

**Comment by aaliboyev** [comment]
This issue needs attention. When you use `Element` inside custom component it throws error.

**Comment by danielbattat** [comment]
I fixed this by ensuring my `Container` was listed in the resolver list.

`<Editor resolver={{Button, Text, Container}}> .... </Editor> `

**Comment by wuichen** [comment]
> I fixed this by ensuring my `Container` was listed in the resolver list.
> 
> `<Editor resolver={{Button, Text, Container}}> .... </Editor> `

why would this resolve the issue

**Comment by WilsonLe** [comment]
> I fixed this by ensuring my `Container` was listed in the resolver list.
> 
> 
> 
> `<Editor resolver={{Button, Text, Container}}> .... </Editor> `

The reproduce code sandbox I created above (https://codesandbox.io/s/craftjs-cond-element-9szcsl) clearly has `Container` in the `Resolver` list and yet the issue persists.

**Comment by Yhozen** [comment]
The issue is about craft.js not resolving the default "div"
I got the following error

![image](https://github.com/prevwong/craft.js/assets/6902134/37af0df2-d665-4b3b-9a2a-7b43ddda205d)
 
and looking the dist folder from node_modules I was able to confirm that it was the div
![image](https://github.com/prevwong/craft.js/assets/6902134/3299ba1b-5799-4981-a63a-e502ab0a1fba)
Also the [source code indicates that div is the default "is" value ](https://github.com/prevwong/craft.js/blob/56ec2227092f67472ddb4511562e7f5abd58130e/packages/core/src/nodes/Element.tsx#L12)

So I finally fixed it by creating a dumb Div component

```tsx
import type { DetailedHTMLProps, HTMLAttributes } from 'react'
import { type Node, useNode } from '@craftjs/core'

export const Div = (
  props: DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>,
) => {
  const {
    connectors: { connect, drag },
  } = useNode()

  return <div {...props} ref={ref => connect(drag(ref!))} />
}

Div.craft = {
  rules: {
    canDrag: (node: Node) => node.data.props.text !== 'Drag',
  },
}

```
then I passed the Div component to the editor component

```tsx
      <Editor resolver={{ Card, Button, Text, Container, Div }}>
```

and finally where I was using Element without a "is" prop I changed it to 

```tsx
   <Element is={Div} id="text" canvas>
```

I hope this is useful for someone

**Comment by benhexie** [comment]
@Yhozen Dammnnnn!.... This is God-tier debugging! 🙌 I had to follow immediately.

**Comment by benhexie** [comment]
This btw doesn't work

> The issue is about craft.js not resolving the default "div" I got the following error
> 
> ![image](https://private-user-images.githubusercontent.com/6902134/306107719-37af0df2-d665-4b3b-9a2a-7b43ddda205d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NTY0NDQsIm5iZiI6MTcwODQ1NjE0NCwicGF0aCI6Ii82OTAyMTM0LzMwNjEwNzcxOS0zN2FmMGRmMi1kNjY1LTRiM2ItOWEyYS03YjQzZGRkYTIwNWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjBUMTkwOTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTMzZWE4NTNjYmJiZmY4YjM1OGE1ZDlkNWQzMGVlNGI1M2Y0MGViMTQ4MWQxODJmZmJlZTFmZGFhMmQ5YTdjNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mG3gr5eSIW4878GLG81JXBwXAgDYYy7cr1oQQVcqS0I)
> 
> and looking the dist folder from node_modules I was able to confirm that it was the div ![image](https://private-user-images.githubusercontent.com/6902134/306107840-3299ba1b-5799-4981-a63a-e502ab0a1fba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NTY0NDQsIm5iZiI6MTcwODQ1NjE0NCwicGF0aCI6Ii82OTAyMTM0LzMwNjEwNzg0MC0zMjk5YmExYi01Nzk5LTQ5ODEtYTYzYS1lNTAyYWIwYTFmYmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjBUMTkwOTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjgxMjUwNGM5OGI2OTdiODAzNTdjNDZiMjQyNDQ4ZWZhMjYxZjgyZWI2MThhMDRiZDY4ZjAwYTdlYTgxODI0MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0BKIkIJfkJW75dOQokrtz5oXgPc3WX1Ro8KWQkU4Eo4) Also the [source code indicates that div is the default "is" value ](https://github.com/prevwong/craft.js/blob/56ec2227092f67472ddb4511562e7f5abd58130e/packages/core/src/nodes/Element.tsx#L12)
> 
> So I finally fixed it by creating a dumb Div component
> 
> ```tsx
> import type { ComponentProps } from 'react'
> import { type Node, useNode } from '@craftjs/core'
> 
> export const Div = (
>   props: ComponentProps<'div'>,
> ) => {
>   const {
>     connectors: { connect, drag },
>   } = useNode()
> 
>   return <div {...props} ref={ref => connect(drag(ref!))} />
> }
> 
> Div.craft = {
>   rules: {
>     canDrag: (node: Node) => node.data.props.text !== 'Drag',
>   },
> }
> ```
> 
> then I passed the Div component to the editor component
> 
> ```tsx
>       <Editor resolver={{ Card, Button, Text, Container, Div }}>
> ```
> 
> and finally where I was using Element without a "is" prop I changed it to
> 
> ```tsx
>    <Element is={Div} id="text" canvas>
> ```
> 
> I hope this is useful for someone

**Comment by Yhozen** [comment]
What kind of error are you getting? It is working fine for me now
> This btw doesn't work

**Comment by benhexie** [comment]
```error
Invariant failed: The component type specified for this node (ke2) does not exist in the resolver. 
```
I've been testing on [WilsonLe's sandbox](https://codesandbox.io/s/craftjs-cond-element-9szcsl) to no avail. You could try working on the sandbox and share a link to yours if you're successful. It would be very helpful 🙏

> What kind of error are you getting? It is working fine for me now
> 
> > This btw doesn't work

**Comment by CarlosLukass** [comment]
You just need to add the "Element" Component into your Resolver @benhexie, that is how I fix the issue. :)
