### ISSUE TITLE
Linked nodes aren't properly rendered when added manually

### ISSUE THREAD

**Issue by hdaggett** [prevwong/craft.js#98]
I'm saving/loading node trees to a database, and everything is working except for linked nodes. When I use `actions.addNodeTree` to add a node that includes editable canvases, the content in those canvases is replaced by the default content specified in the UserComponent.

Using the example from the docs:
```
const Hero = ({background}) => {
  return (
    <div style={{ background }}>
      <Element is={Text} text="Hero Title" id="title_text" />
      <Element canvas is="section" id="droppable_container">
        <h2>I'm dropped here for now</h2>
      </Element>
    </div>
  )
}
```

If I were to manually add a node tree where the `<h2>` was replaced with some other content, it would instead load the `<h2>I'm dropped here for now</h2>` that's defined above.

**Comment by prevwong** [comment]
Hey @hdaggett 👋

If I understand correctly, you're adding a new Node which contains linked nodes. But when the User Component of the Node you're adding gets rendered, the linked Nodes inside the component loads the default content instead, right? If so, that's pretty weird and shouldn't happen. Could you share a snippet of how you're calling `actions.addNodeTree`?

**Comment by hdaggett** [comment]
Hi @prevwong , thank you for the quick response! Yes that sounds exactly right.

Here is the NodeTree I'm adding:
```
{
   "rootNodeId":"wygqxNu2B",
   "nodes":{
      "HvvyueGqV":{
         "id":"nbovmEU4SE",
         "_hydrationTimestamp":1594401887696,
         "data":{
            "name":"CgdsButton",
            "displayName":"CGDS Button",
            "props":{
               "children":"Button"
            },
            "custom":{

            },
            "isCanvas":false,
            "hidden":false,
            "parent":"wygqxNu2B",
            "linkedNodes":{
               "field-label":"BG0hYmm6J"
            }
         },
         "related":{

         },
         "events":{
            "selected":false,
            "dragged":false,
            "hovered":false
         },
         "rules":{

         }
      },
      "wygqxNu2B":{
         "id":"LrQr1ev7_A",
         "_hydrationTimestamp":1594401887696,
         "data":{
            "name":"Page",
            "displayName":"Page",
            "props":{
               "id":"4cbcce14-3197-4457-b575-1b43563c49b5"
            },
            "custom":{

            },
            "isCanvas":true,
            "hidden":false,
            "parent":"ROOT",
            "nodes":[
               "HvvyueGqV"
            ]
         },
         "related":{

         },
         "events":{
            "selected":false,
            "dragged":false,
            "hovered":false
         },
         "rules":{

         }
      },
      "WeUE1p4MGJ":{
         "id":"fTS_D-2Mox",
         "_hydrationTimestamp":1594401887696,
         "data":{
            "name":"Text",
            "displayName":"Text",
            "props":{
               "text":"Test content"
            },
            "custom":{

            },
            "isCanvas":false,
            "hidden":false,
            "parent":"BG0hYmm6J"
         },
         "related":{

         },
         "events":{
            "selected":false,
            "dragged":false,
            "hovered":false
         },
         "rules":{

         }
      },
      "BG0hYmm6J":{
         "id":"JQw39YrRdg",
         "_hydrationTimestamp":1594401887697,
         "data":{
            "name":"Container",
            "displayName":"Container",
            "props":{

            },
            "custom":{

            },
            "isCanvas":true,
            "hidden":false,
            "parent":"HvvyueGqV",
            "nodes":[
               "WeUE1p4MGJ"
            ]
         },
         "related":{

         },
         "events":{
            "selected":false,
            "dragged":false,
            "hovered":false
         },
         "rules":{

         }
      }
   }
}
```

And I'm adding it simply using `actions.addNodeTree(nodeTree, "ROOT");` where `nodeTree` is defined above.

In the NodeTree above, the text node `WeUE1p4MGJ` has `props.text = "Test Content"`, but it still gets rendered with "Lorem Ipsum" which is the default content.

Here's a snippet from the UserComponent:
```
const ButtonComponent = ({ style, ...props }) => {
  const {
    connectors: { connect, drag },
    selected,
    dragged,
    setProp,
  } = useNode((state) => ({
    selected: state.events.selected,
    dragged: state.events.dragged,
  }));
  const { enabled } = useEditor((state) => ({
    enabled: state.options.enabled,
  }));

  return (
    <Button
      ref={(ref) => connect(drag(ref))}
      {...props}
      fullWidth={props.fullWidth == "responsive" || eval(props.fullWidth)}
    >
      <Canvas id="field-label" is={Container}>
        <TextComponent text="Lorem ipsum" />
      </Canvas>
    </Button>
  );
};
```

**Comment by prevwong** [comment]
@hdaggett Fixed in beta.9! 🥳 

On another note, based on your example - I think we should probably introduce a helper function to allow developers to easily create a valid Node rather than having to manually create the object and ensuring all the necessary properties are there 😄

**Comment by hdaggett** [comment]
Hey @prevwong, I seem to still have issues with linked nodes in 0.1.0-beta.10 ... Not sure what is going on, but it seems like it's failing here because node is undefined?

https://github.com/prevwong/craft.js/blob/31a5e97c0c947c83f7422ff7a6d54376b1d79f6a/packages/core/src/editor/actions.ts#L50

Also your comment on the helper function - I'm using `query.parseSerializedNode(node).toNode();` for that... not sure if that's right or not.

Here's the NodeTree I'm passing to `actions.addNodeTree`:

```
{
   "rootNodeId":"4MnlLupRW",
   "nodes":{
      "2KG03Q74k":{
         "id":"W0lbJn7PN",
         "_hydrationTimestamp":1595453753651,
         "data":{
            "props":{
               "children":"Button"
            },
            "name":"CgdsButton",
            "displayName":"CGDS Button",
            "custom":{

            },
            "isCanvas":false,
            "hidden":false,
            "parent":"4MnlLupRW",
            "linkedNodes":{
               "field-label":"4tUtRoKyp"
            }
         },
         "related":{

         },
         "events":{
            "selected":false,
            "dragged":false,
            "hovered":false
         },
         "rules":{

         }
      },
      "hMDSqj7LkU":{
         "id":"uwdNwQsCpk",
         "_hydrationTimestamp":1595453753651,
         "data":{
            "props":{
               "text":"My button text here"
            },
            "name":"Text",
            "displayName":"Text",
            "custom":{

            },
            "isCanvas":false,
            "hidden":false,
            "parent":"4tUtRoKyp"
         },
         "related":{

         },
         "events":{
            "selected":false,
            "dragged":false,
            "hovered":false
         },
         "rules":{

         }
      },
      "4MnlLupRW":{
         "id":"DWkA1HjALB",
         "_hydrationTimestamp":1595453753652,
         "data":{
            "props":{
               "id":"2647faf0-5d78-403b-8af9-0d2761a528f8"
            },
            "name":"Page",
            "displayName":"Page",
            "custom":{

            },
            "isCanvas":true,
            "hidden":false,
            "parent":"ROOT",
            "nodes":[
               "2KG03Q74k"
            ]
         },
         "related":{

         },
         "events":{
            "selected":false,
            "dragged":false,
            "hovered":false
         },
         "rules":{

         }
      },
      "4tUtRoKyp":{
         "id":"hdDpkx8Lqy",
         "_hydrationTimestamp":1595453753652,
         "data":{
            "props":{

            },
            "name":"Container",
            "displayName":"Container",
            "custom":{

            },
            "isCanvas":true,
            "hidden":false,
            "parent":"2KG03Q74k",
            "nodes":[
               "hMDSqj7LkU"
            ]
         },
         "related":{

         },
         "events":{
            "selected":false,
            "dragged":false,
            "hovered":false
         },
         "rules":{

         }
      }
   }
}
```

**Comment by hdaggett** [comment]
Turns out this was on my end - I was using `query.parseSerializedNode(node).toNode()` which I think used to preserve node IDs, but as you can see above the `id` properties are different from the object keys in `nodes`... I fixed it by passing a function to `toNode` to preserve the node ID:

`query.parseSerializedNode(node).toNode(node => node.id = id)`

**Comment by Tashows** [comment]
@hdaggett Hey could you help me out a bit? I am trying to do something similar. How do you save and then load nodeTrees? While I am able to create a nodeTree and add it to the editor, if I try to save it to the database and then load it again it won't work. I realized it's because some functions are removed when stringifying the json (type is removed and then cannot be parsed correctly), but still can't figure out what the right way is.

**Comment by hdaggett** [comment]
@Tashows You'll want to serialize the nodes before saving, and then deserialize after saving and add the deserialized `nodeTree` to the ROOT node. 

### Serializing before saving
You might be able to do this with just `query.getSerializedNodes()`. In my case, I needed to separate into `nodeTree`s (because my ROOT node has multiple "pages" which can also be rendered independently).

Code for serializing multiple `nodeTree`s before saving (I call this from the `Editor`'s `onNodesChange` event, passing `query`)
```
getSerializedPageNodes = (query) => {
  // Get current nodes
  const allNodes = query.getSerializedNodes();
  const rootNode = query.node("ROOT").get();
  const pageNodes = rootNode.data.nodes;
  if (!pageNodes) return;
  const nodeArray = pageNodes.map((nodeId) => {
    const pageNode = query.node(nodeId);
    const pageNodeTree = pageNode.toNodeTree();
    const serializedNodes = nodesToSerializedNodes(
      pageNodeTree.nodes,
      allNodes
    );
    return {
      rootNodeId: nodeId,
      nodes: {
        [nodeId]: allNodes[nodeId],
        ...serializedNodes,
      },
    };
  });

  var pagesObject = {};
  pageNodes.forEach((nodeId, index) => {
    pagesObject[nodeId] = nodeArray[index];
  });
  return pagesObject;
};
```
### Deserializing after saving
Where `serializedTree` is a JSON tree as saved above and `query` is from the `useEditor` hook:
```
serializedTreeToNodeTree = (serializedTree, query) => {
  var nodeTree = { ...serializedTree };
  Object.keys(serializedTree.nodes).forEach((nodeId) => {
    nodeTree.nodes[nodeId] = query
      .parseSerializedNode(serializedTree.nodes[nodeId])
      .toNode((node) => (node.id = nodeId));
  });
  return nodeTree;
};
```
### Add the `nodeTree` to the ROOT node:
```
actions.addNodeTree(pageNodeTree, "ROOT");
```

This took a lot of trial and error, and I haven't updated Craft in a while so maybe there's a better way. Hope this helps!

**Comment by Tashows** [comment]
@hdaggett Thanks a lot! That's roughly the workflow I was thinking of implementing manually. I'll go this way then, your input has been very helpful!
@prevwong, I know this might be of topic, but maybe in the future this can become a craft method like getSerializedNoteTree(rootNodeId), where rootNodeId can be the root node you want to convert into a serialized nodeTree?
